name: Tests

on:
  push:
    branches: ['master']

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.0]

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          php_version: "8.0"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Test utils
        with:
          php_version: "8.0"
          version: "9.5.16"
          bootstrap: vendor/autoload.php
          args: --coverage-text
          configuration: "./phpunit.xml"
